name: Laravel Tests

on: [push]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0' 

    - name: Install Composer dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Copy .env file
      run: cp .env.example .env

    - name: Generate application key
      run: php artisan key:generate

    - name: Run PHPUnit tests
      run: vendor/bin/phpunit

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: ./tests/Reports
